[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
bytecode_hash = 'none'

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}", chain = "arbitrum-sepolia", url = "https://api-sepolia.arbiscan.io/api"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config