name: CI

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install ZKSync Foundry
        uses: dutterbutter/foundry-zksync-toolchain@v1

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Hardhat
        run: pnpm compile

      - name: Style
        run: pnpm style

      - name: Forge Build
        run: pnpm forge-build

      - name: Forge Fmt
        run: pnpm forge-fmt

      - name: Test Hardhat
        run: pnpm test:hardhat

      - name: Forge Test
        run: pnpm test:forge



